In [118]:
import pandas as pd
import numpy as np

In [119]:
import requests
import pandas as pd

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": 50.08,
    "longitude": 7.76,
    "start_date": "2000-01-01",
    "end_date": "2026-09-01",
    "hourly": (
        "temperature_2m,"
        "relative_humidity_2m,"
        "precipitation,"
        "rain,"
        "snowfall,"
        "pressure_msl,"
        "wind_speed_10m,"
        "wind_direction_10m,"
        "et0_fao_evapotranspiration"
    ),
    "timezone": "Europe/Berlin"
}

response = requests.get(url, params=params)

data = response.json()

weather = pd.DataFrame(data["hourly"])

weather["time"] = pd.to_datetime(weather["time"])

print(weather.head())
print(weather.shape)

                 time  temperature_2m  relative_humidity_2m  precipitation  \
0 2000-01-01 00:00:00             1.9                    96            0.0
1 2000-01-01 01:00:00             1.7                    96            0.0
2 2000-01-01 02:00:00             1.5                    97            0.0
3 2000-01-01 03:00:00             1.4                    97            0.0
4 2000-01-01 04:00:00             1.5                    97            0.0

   rain  snowfall  pressure_msl  wind_speed_10m  wind_direction_10m  \
0   0.0       0.0        1024.5             5.9                 194
1   0.0       0.0        1025.0             5.4                 180
2   0.0       0.0        1024.7             6.9                 189
3   0.0       0.0        1024.6             6.6                 202
4   0.0       0.0        1025.0             6.6                 221

   et0_fao_evapotranspiration
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0
(233784, 10)

In [120]:
weather.head()

,time,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m,wind_direction_10m,et0_fao_evapotranspiration
0,2000-01-01 00:00:00,1.9,96,0.0,0.0,0.0,1024.5,5.9,194,0.0
1,2000-01-01 01:00:00,1.7,96,0.0,0.0,0.0,1025.0,5.4,180,0.0
2,2000-01-01 02:00:00,1.5,97,0.0,0.0,0.0,1024.7,6.9,189,0.0
3,2000-01-01 03:00:00,1.4,97,0.0,0.0,0.0,1024.6,6.6,202,0.0
4,2000-01-01 04:00:00,1.5,97,0.0,0.0,0.0,1025.0,6.6,221,0.0

In [121]:
weather.shape

(233784, 10)

In [122]:
#Checking for the address
import os

print(os.getcwd())

c:\Users\Prithvi Hegde\neuefische_course\HydroLoad-AI\notebooks

In [123]:
#checking for the address
import os

print(os.path.exists("data/raw/water_level_15min_kaub.csv"))
print(os.path.exists("../data/raw/water_level_15min_kaub.csv"))

False
True

In [124]:
# Read CSV file for water level for every 15 min
df_water15 = pd.read_csv("../data/raw/water_level_15min_kaub.csv")

df_water15.head()

        timestamp;value
0  2000-01-01 01:00;459
1  2000-01-01 01:15;458
2  2000-01-01 01:30;458
3  2000-01-01 01:45;458
4  2000-01-01 02:00;457

In [125]:
# Read without semicolon
df_water15 = pd.read_csv("../data/raw/water_level_15min_kaub.csv",sep=";")

df_water15.head()

          timestamp  value
0  2000-01-01 01:00    459
1  2000-01-01 01:15    458
2  2000-01-01 01:30    458
3  2000-01-01 01:45    458
4  2000-01-01 02:00    457

In [126]:
# Convert timestamp to datetime
df_water15["timestamp"] = pd.to_datetime(df_water15["timestamp"])

# 15-minute  to hourly mean
df_water_hourly = (
    df_water15
    .set_index("timestamp")
    .resample("1h")["value"]
    .mean()
    .reset_index()
)

df_water_hourly.head()

            timestamp   value
0 2000-01-01 01:00:00  458.25
1 2000-01-01 02:00:00  456.75
2 2000-01-01 03:00:00  455.00
3 2000-01-01 04:00:00  453.00
4 2000-01-01 05:00:00  451.00

In [127]:
# Make sure timestamp is datetime
df_water_hourly["timestamp"] = pd.to_datetime(df_water_hourly["timestamp"])

# Create separate date and time columns
df_water_hourly["date"] = df_water_hourly["timestamp"].dt.date
df_water_hourly["time"] = df_water_hourly["timestamp"].dt.time

# Keep the required columns
df_hourly_water = df_water_hourly[["date", "time", "value"]]

df_hourly_water.head()

         date      time   value
0  2000-01-01  01:00:00  458.25
1  2000-01-01  02:00:00  456.75
2  2000-01-01  03:00:00  455.00
3  2000-01-01  04:00:00  453.00
4  2000-01-01  05:00:00  451.00

In [128]:
# shape of hourly water level data
df_hourly_water.shape

(233783, 3)

In [129]:
weather.head()

,time,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m,wind_direction_10m,et0_fao_evapotranspiration
0,2000-01-01 00:00:00,1.9,96,0.0,0.0,0.0,1024.5,5.9,194,0.0
1,2000-01-01 01:00:00,1.7,96,0.0,0.0,0.0,1025.0,5.4,180,0.0
2,2000-01-01 02:00:00,1.5,97,0.0,0.0,0.0,1024.7,6.9,189,0.0
3,2000-01-01 03:00:00,1.4,97,0.0,0.0,0.0,1024.6,6.6,202,0.0
4,2000-01-01 04:00:00,1.5,97,0.0,0.0,0.0,1025.0,6.6,221,0.0

In [130]:
# Convert to datetime
weather["time"] = pd.to_datetime(weather["time"])

# Create separate date and time columns
weather["date"] = weather["time"].dt.date
weather["time_only"] = weather["time"].dt.time

# Remove original datetime column
weather = weather.drop(columns=["time"])

# Rename time_only to time
weather = weather.rename(columns={"time_only": "time"})

In [131]:
weather = weather[
    ["date", "time"] +
    [col for col in weather.columns if col not in ["date", "time"]]
]

weather.head()

,date,time,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m,wind_direction_10m,et0_fao_evapotranspiration
0,2000-01-01,00:00:00,1.9,96,0.0,0.0,0.0,1024.5,5.9,194,0.0
1,2000-01-01,01:00:00,1.7,96,0.0,0.0,0.0,1025.0,5.4,180,0.0
2,2000-01-01,02:00:00,1.5,97,0.0,0.0,0.0,1024.7,6.9,189,0.0
3,2000-01-01,03:00:00,1.4,97,0.0,0.0,0.0,1024.6,6.6,202,0.0
4,2000-01-01,04:00:00,1.5,97,0.0,0.0,0.0,1025.0,6.6,221,0.0

In [132]:
#drop first row due to time mismatch with water level data
weather = weather.iloc[1:].reset_index(drop=True)

weather.head()

,date,time,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m,wind_direction_10m,et0_fao_evapotranspiration
0,2000-01-01,01:00:00,1.7,96,0.0,0.0,0.0,1025.0,5.4,180,0.0
1,2000-01-01,02:00:00,1.5,97,0.0,0.0,0.0,1024.7,6.9,189,0.0
2,2000-01-01,03:00:00,1.4,97,0.0,0.0,0.0,1024.6,6.6,202,0.0
3,2000-01-01,04:00:00,1.5,97,0.0,0.0,0.0,1025.0,6.6,221,0.0
4,2000-01-01,05:00:00,1.4,97,0.0,0.0,0.0,1025.0,5.9,218,0.0

In [133]:
# Save processed weather data
weather.to_csv("../data/processed/kaub_weather_hourly.csv",index=False)

In [134]:
#water level hourly data
df_hourly_water.head(20)

          date      time   value
0   2000-01-01  01:00:00  458.25
1   2000-01-01  02:00:00  456.75
2   2000-01-01  03:00:00  455.00
3   2000-01-01  04:00:00  453.00
4   2000-01-01  05:00:00  451.00
5   2000-01-01  06:00:00  449.50
6   2000-01-01  07:00:00  447.50
7   2000-01-01  08:00:00  445.00
8   2000-01-01  09:00:00  443.00
9   2000-01-01  10:00:00  441.75
10  2000-01-01  11:00:00  440.25
11  2000-01-01  12:00:00  437.75
12  2000-01-01  13:00:00  437.25
13  2000-01-01  14:00:00  435.50
14  2000-01-01  15:00:00  433.75
15  2000-01-01  16:00:00  431.75
16  2000-01-01  17:00:00  430.50
17  2000-01-01  18:00:00  429.25
18  2000-01-01  19:00:00  427.25
19  2000-01-01  20:00:00  425.75

In [135]:
# Save hourly water level data to processed folder
df_hourly.to_csv("../data/processed/kaub_water_level_hourly.csv",index=False)

In [136]:
#Checking for the NA's and duplicates
print(df_hourly.shape)
print(weather.shape)

print(df_hourly.isna().sum())
print(weather.isna().sum())

print(df_hourly.duplicated().sum())
print(weather.duplicated().sum())

(233783, 3)
(233783, 11)
date      0
time      0
value    27
dtype: int64
date                          0
time                          0
temperature_2m                0
relative_humidity_2m          0
precipitation                 0
rain                          0
snowfall                      0
pressure_msl                  0
wind_speed_10m                0
wind_direction_10m            0
et0_fao_evapotranspiration    0
dtype: int64
0
0

In [137]:
# Checking for the date and time of both the dataset
print(df_hourly[["date", "time"]].head(10))
print(weather[["date", "time"]].head(10))

         date      time
0  2000-01-01  01:00:00
1  2000-01-01  02:00:00
2  2000-01-01  03:00:00
3  2000-01-01  04:00:00
4  2000-01-01  05:00:00
5  2000-01-01  06:00:00
6  2000-01-01  07:00:00
7  2000-01-01  08:00:00
8  2000-01-01  09:00:00
9  2000-01-01  10:00:00
         date      time
0  2000-01-01  01:00:00
1  2000-01-01  02:00:00
2  2000-01-01  03:00:00
3  2000-01-01  04:00:00
4  2000-01-01  05:00:00
5  2000-01-01  06:00:00
6  2000-01-01  07:00:00
7  2000-01-01  08:00:00
8  2000-01-01  09:00:00
9  2000-01-01  10:00:00

In [138]:
#checking for the date and time of the whole dataset
same_date = df_hourly["date"].reset_index(drop=True).equals(
    weather["date"].reset_index(drop=True)
)

same_time = df_hourly["time"].reset_index(drop=True).equals(
    weather["time"].reset_index(drop=True)
)

print("Dates are same:", same_date)
print("Times are same:", same_time)

Dates are same: True
Times are same: True

In [139]:
# One Final check for the missing data
water_times = set(zip(df_hourly["date"], df_hourly["time"]))
weather_times = set(zip(weather["date"], weather["time"]))

print("Missing in weather:", len(water_times - weather_times))
print("Missing in water:", len(weather_times - water_times))

Missing in weather: 0
Missing in water: 0

In [140]:
#Merge both data set
merged_df = pd.merge(
   df_hourly_water,
    weather,
    on=["date", "time"],
    how="inner"
)

merged_df.head()

,date,time,value,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m,wind_direction_10m,et0_fao_evapotranspiration
0,2000-01-01,01:00:00,458.25,1.7,96,0.0,0.0,0.0,1025.0,5.4,180,0.0
1,2000-01-01,02:00:00,456.75,1.5,97,0.0,0.0,0.0,1024.7,6.9,189,0.0
2,2000-01-01,03:00:00,455.00,1.4,97,0.0,0.0,0.0,1024.6,6.6,202,0.0
3,2000-01-01,04:00:00,453.00,1.5,97,0.0,0.0,0.0,1025.0,6.6,221,0.0
4,2000-01-01,05:00:00,451.00,1.4,97,0.0,0.0,0.0,1025.0,5.9,218,0.0

In [141]:
print("water level:", df_hourly_water.shape)
print("Weather:", weather.shape)
print("Merged:", merged_df.shape)

water level: (233783, 3)
Weather: (233783, 11)
Merged: (233783, 12)

In [142]:
merged_df.to_csv("../data/processed/kaub_water_weather_hourly.csv",index=False)